name: serverless_dart_template
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  aws_dynamodb_api: null
  aws_lambda_dart_runtime: ^1.1.0


dev_dependencies:
  build_runner:
  lints:
