service: serverless-dart-template
provider:
  name: aws
  deploymentMethod: direct
  runtime: provided.al2
  region: your-aws-region

package:
  individually: true
  artifact: build/bootstrap.zip

plugins:
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3

functions:
  status:
    handler: main.status
    events:
      - http:
          path: /status
          method: GET
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Content-Encoding