name: Main
on: push

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::XXXXXXXX:role/GitHub_Deploy
          aws-region: your-aws-region
      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get -y install apt-transport-https
          wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/dart.gpg
          echo 'deb [signed-by=/usr/share/keyrings/dart.gpg arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main' | sudo tee /etc/apt/sources.list.d/dart_stable.list
          sudo apt-get update
          sudo apt-get -y install dart zip
          npm install -g serverless@latest

      - name: Deploy
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          mkdir build
          npm install --save-dev aws-sdk@latest
          npx serverless plugin install --name serverless-iam-roles-per-function
          npx serverless plugin install --name serverless-prune-plugin
          dart pub get
          dart run build_runner build --delete-conflicting-outputs
          dart compile exe lib/main.dart -o build/bootstrap
          cd build
          zip bootstrap.zip ./*
          cd ..
          npx serverless deploy
